# Generated by Django 5.1.7 on 2025-05-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annonce',
            old_name='vendeur',
            new_name='User',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='acheteur', max_length=100),
        ),
    ]
