# Generated by Django 5.2 on 2025-05-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_vendeur_annonce_user_alter_utilisateur_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annonce',
            old_name='User',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(max_length=100),
        ),
    ]
